---
# Source: pages/charts/mysql/templates/secret.yaml
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: alpha-mysql
---
# Source: pages/charts/pages-api/templates/secret.yaml
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: alpha-pages-api
---
# Source: pages/charts/mysql/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpha-mysql
data:
  spring.datasource.username: root
  V1__inital_schema.sql: |
    USE pages;
    create table pages(
    id bigint(20) not null auto_increment,
    business_name VARCHAR(50),
    address VARCHAR(50),
    category_id bigint(20),
    contact_number VARCHAR(50),
    primary key (id)
    )
    engine = innodb
    default charset = utf8;
---
# Source: pages/charts/pages-api/templates/config.yaml
apiVersion: v1
data:
  PAGE_CONTENT: Green-Pages coming from Yellow-World!
kind: ConfigMap
metadata:
  name: pages-api
---
# Source: pages/charts/mysql/templates/storage-class.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: alpha-mysql-brixton
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
# Source: pages/charts/mysql/templates/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alpha-mysql-brixton
  labels:
    type: local
spec:
  storageClassName: alpha-mysql-brixton
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/mysql/brixton
---
# Source: pages/charts/mysql/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpha-mysql
spec:
  storageClassName: alpha-mysql-brixton
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# Source: pages/charts/mysql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pages-mysql
  labels:
    app: alpha-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: alpha-mysql
  type: ClusterIP
---
# Source: pages/charts/pages-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alpha-pages-api
    access: external
  name: alpha-pages-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alpha-pages-api
  type: NodePort
---
# Source: pages/charts/mysql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-mysql
  labels:
    app: alpha-mysql
spec:
  selector:
    matchLabels:
      app: alpha-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alpha-mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alpha-mysql
                  key: password
            - name: MYSQL_SERVICE_HOST
              value: "mysql"
            - name: MYSQL_SERVICE_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "pages"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: alpha-mysql
---
# Source: pages/charts/pages-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-pages-api
  name: alpha-pages-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-pages-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: alpha-pages-api
    spec:
      containers:
        - image: dellcloud/pages:monitor
          name: pages-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PAGE_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: pages-api
                  key: PAGE_CONTENT
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://pages-mysql/pages"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alpha-pages-api
                  key: password
            - name: DEBUG
              value: "true"
            - name: LOGGING_FILE_NAME
              value: "brixton/logs/app.log"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              value: debug
            - name: LOGGING_LEVEL_ROOT
              value: debug
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
          volumeMounts:
            - name: node-dir
              mountPath: /brixton
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: node-dir
          hostPath:
            path: /brixton
---
# Source: pages/charts/mysql/templates/flyway-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: alpha-mysql
  labels:
    app: alpha-mysql
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 16
  template:
    spec:
      containers:
        - name: mysql
          image: flyway/flyway:6.4.4
          imagePullPolicy: IfNotPresent
          args:
            - info
            - migrate
            - info
          env:
            - name: FLYWAY_URL
              value: "jdbc:mysql://pages-mysql/pages"
            - name: FLYWAY_USER
              value: root
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alpha-mysql
                  key: password
            - name: FLYWAY_PLACEHOLDER_REPLACEMENT
              value: "true"
            - name: FLYWAY_PLACEHOLDERS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: alpha-mysql
                  key: spring.datasource.username
            - name: FLYWAY_PLACEHOLDERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alpha-mysql
                  key: password
          volumeMounts:
            - mountPath: /flyway/sql
              name: sql
      volumes:
        - name: sql
          configMap:
            name: alpha-mysql
      restartPolicy: Never
